export const CATEGORIES = [
  { id: "arts", label: "Arts" },
  { id: "book_clubs", label: "Book Clubs" },
  { id: "business", label: "Business" },
  { id: "causes", label: "Causes" },
  { id: "comedy", label: "Comedy" },
  { id: "crafts", label: "Crafts" },
  { id: "food_drink", label: "Food & Drink" },
  { id: "health", label: "Health" },
  { id: "music", label: "Music" },
  { id: "auto_boat_air", label: "Auto, Boat & Air" },
  { id: "community", label: "Community" },
  { id: "family_education", label: "Family & Education" },
  { id: "fashion_beauty", label: "Fashion & Beauty" },
  { id: "film_media", label: "Film & Media" },
  { id: "games", label: "Games" },
  { id: "language_culture", label: "Language & Culture" },
  { id: "learning", label: "Learning" },
  { id: "lgbtq", label: "LGBTQ" },
  { id: "movements_politics", label: "Movements & Politics" },
  { id: "networking", label: "Networking" },
  { id: "party", label: "Party" },
  { id: "performing_visual_arts", label: "Performing & Visual Arts" },
  { id: "pets", label: "Pets" },
  { id: "photography", label: "Photography" },
  { id: "outdoors_adventure", label: "Outdoors & Adventure" },
  { id: "spirituality_religion_beliefs", label: "Spirituality, Religion & Beliefs" },
  { id: "science_tech", label: "Science & Tech" },
  { id: "sports", label: "Sports" },
  { id: "theatre", label: "Theatre" },
  { id: "meeting", label: "Meeting" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];
